;;; test-diario-commands.el --- Isolated diario command fixtures -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'org)
(require 'diario-commands)

(defvar denote-journal-directory)

(defconst my-dct-test--setup
  (expand-file-name "setup-journaling.el"
                    (expand-file-name ".." (file-name-directory
                                             (or load-file-name buffer-file-name)))))

(defconst my-dct-test--source
  "#+title: Ayer\n#+identifier: 20260601T1100\n\n* OPORTUNIDADES Y AMENAZAS\n** Empresa\n*** TODO Encargo :cliente_001:\n** Contratista\n* DEEP\n** TODO Trabajo\nCuerpo y [[denote:20260511T1358]].\n* SHALLOW\n** COLD Más tarde\nSCHEDULED: <2026-06-20 Sat>\n* Notas\nTexto fuera de listas.\n")

(defconst my-dct-test--fresh
  "#+title: Hoy\n#+date: [2026-06-03 Wed]\n#+filetags: :journal:\n#+identifier: 20260603T0900\n\n")

(defconst my-dct-test--ready
  "#+title: Hoy\n#+date: [2026-06-03 Wed]\n#+identifier: 20260603T0900\n\n* OPORTUNIDADES Y AMENAZAS\n** Empresa\n*** TODO Decisión de hoy\n** Contratista\n* DEEP\n** NEXT Elección de hoy\n* SHALLOW\n* Notas\nEditado hoy.\n")

(defconst my-dct-test--refile-layout
  "#+title: Hoy\n#+identifier: 20260603T0900\n\n* OPORTUNIDADES Y AMENAZAS :area:\n** Empresa :empleo:\n** Contratista\n* DEEP :trabajo:\n* SHALLOW\n* Notas\n** Empresa :impostor:\n** Contratista\n* Otra sección\n** DEEP :impostor:\n")

(defun my-dct-test--assert-dir (dir)
  "Refuse diario operations outside temporary fixture DIR."
  (unless (and (stringp denote-journal-directory)
               (equal (file-name-as-directory
                       (expand-file-name denote-journal-directory))
                      (file-name-as-directory (expand-file-name dir))))
    (error "Diario fixture escaped %s: %S" dir denote-journal-directory)))

(defmacro my-dct-test--with-files (&rest body)
  "Run BODY with disposable diarios, no hooks, and a fixed command date."
  (declare (indent 0) (debug t))
  `(with-temp-buffer
     (let* ((dir (make-temp-file "diario-commands-test-" t))
            (denote-journal-directory dir)
            (source (expand-file-name "20260601T1100--ayer__journal.org" dir))
            (target (expand-file-name "20260603T0900--hoy__journal.org" dir))
            (later (expand-file-name "LUEGO.org" dir))
            (real-clock (symbol-function 'format-time-string))
            (real-files (symbol-function 'my-dc--files))
            (real-later (symbol-function 'my-dc--later))
            (real-find (symbol-function 'find-file-noselect))
            (org-mode-hook nil)
            (find-file-hook nil)
            (kill-buffer-query-functions nil)
            (org-todo-keywords '((sequence "TODO" "NEXT" "WAIT" "SDM" "COLD"
                                          "PROG" "|" "DONE" "KILL")))
            (org-log-done nil)
            (org-log-reschedule nil)
            (org-inhibit-startup t)
            (org-agenda-files org-agenda-files)
            (org-refile-targets org-refile-targets)
            (org-refile-target-verify-function org-refile-target-verify-function)
            (my-dc--base-refile-verify my-dc--base-refile-verify)
            (org-refile-use-cache nil)
            (org-refile-use-outline-path t))
       (unwind-protect
           (save-window-excursion
             (setq-local denote-journal-directory dir)
             (my-dct-test--assert-dir dir)
             (with-temp-file source (insert my-dct-test--source))
             (cl-letf (((symbol-function 'format-time-string)
                        (lambda (format &optional time zone)
                          (if (and (equal format "%Y%m%d") (null time))
                              "20260603"
                            (funcall real-clock format time zone))))
                       ((symbol-function 'my-dc--files)
                        (lambda ()
                          (my-dct-test--assert-dir dir)
                          (funcall real-files)))
                       ((symbol-function 'my-dc--later)
                        (lambda ()
                          (my-dct-test--assert-dir dir)
                          (funcall real-later)))
                       ((symbol-function 'find-file-noselect)
                        (lambda (file &rest args)
                          (my-dct-test--assert-dir dir)
                          (unless (and (stringp file)
                                       (file-in-directory-p file dir))
                            (error "Diario fixture cannot visit %S" file))
                          (let ((buffer (apply real-find file args)))
                            (with-current-buffer buffer
                              (setq-local denote-journal-directory dir))
                            buffer))))
               ,@body))
         (dolist (file (directory-files dir t "\\.org\\'"))
           (when-let* ((buffer (find-buffer-visiting file)))
             (with-current-buffer buffer
               (let ((kill-buffer-query-functions nil)
                     (kill-buffer-hook nil))
                 (set-buffer-modified-p nil)
                 (kill-buffer buffer)))))
         (delete-directory dir t)))))

(defun my-dct-test--text (file)
  "Read fixture FILE without visiting it."
  (with-temp-buffer
    (insert-file-contents file)
    (buffer-string)))

(defun my-dct-test--count (text item)
  "Count literal ITEM occurrences in TEXT."
  (let ((start 0) (count 0))
    (while (string-match (regexp-quote item) text start)
      (setq start (match-end 0))
      (cl-incf count))
    count))

(defun my-dct-test--due (file &optional date)
  "Write one parked SHALLOW entry to FILE, scheduled on DATE."
  (with-temp-file file
    (insert (format "* LUEGO\n** COLD Esperando\nSCHEDULED: <%s>\n:PROPERTIES:\n:DIARIO_KEY: waiting-1\n:DIARIO_LIST: SHALLOW\n:DIARIO_ORIGIN_HASH: %s\n:END:\nNota anidada.\n"
                    (or date "2026-06-02 Tue")
                    (my-diario--origin-hash "waiting-1" "SHALLOW" nil)))))

(ert-deftest my-diario-commands-wrapper-wiring ()
  ;; Read just the wrapper form; loading setup-journaling would install its
  ;; unrelated PRIAD hooks in the shared Emacs session.
  (with-temp-buffer
    (insert-file-contents my-dct-test--setup)
    (goto-char (point-min))
    (should (re-search-forward "^(defun my-denote-journal-today " nil t))
    (beginning-of-line)
    (let* ((form (read (current-buffer)))
           (wrapper (eval `(lambda ,(nth 2 form) ,@(cdddr form)) t)))
      (should (equal (cddddr form) '((interactive) (my-diario-today))))
      (cl-letf (((symbol-function 'my-diario-today)
                 (lambda () :delegated)))
        (should (eq (funcall wrapper) :delegated))))
    (should (re-search-forward
             "(define-key map (kbd \"C-c n j\") #'my-denote-journal-today)" nil t))
    (goto-char (point-min))
    (should (re-search-forward
             "(add-hook 'org-mode-hook #'my-diario-activate-focus)" nil t))))

(ert-deftest my-diario-commands-fixture-scope ()
  (with-temp-buffer
    (setq-local denote-journal-directory (file-name-directory my-dct-test--setup))
    (my-dct-test--with-files
      (should (equal denote-journal-directory dir))
      (should (null (my-dc--day-files "20260603")))
      (let ((denote-journal-directory (file-name-directory my-dct-test--setup)))
        (cl-letf (((symbol-function 'denote)
                   (lambda (&rest _args)
                     (error "Fixture attempted Denote creation"))))
          (let ((reason (should-error (my-diario-today) :type 'error)))
            (should (string-match-p "Diario fixture escaped"
                                    (error-message-string reason)))))
        (should-not (file-exists-p target)))
      (with-current-buffer (find-file-noselect source)
        (should (equal denote-journal-directory dir))
        (let ((denote-journal-directory (file-name-directory my-dct-test--setup)))
          (let ((reason (should-error (my-diario-refile-targets) :type 'error)))
            (should (string-match-p "Diario fixture escaped"
                                    (error-message-string reason)))))
        (should (equal denote-journal-directory dir)))
      (let ((reason (should-error (find-file-noselect my-dct-test--setup)
                                  :type 'error)))
        (should (string-match-p "Diario fixture cannot visit"
                                (error-message-string reason)))))))

(ert-deftest my-diario-commands-discovery-and-agenda ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--ready))
    (let ((older (expand-file-name "20260530T1700--older__journal.org" dir))
          (other (expand-file-name "20260602T1700--not-a-journal.org" dir))
          (nested (expand-file-name "nested" dir)))
      (with-temp-file older (insert "Old snapshot"))
      (with-temp-file other (insert "Not a diario"))
      (make-directory nested)
      (with-temp-file (expand-file-name "20260603T1800--nested__journal.org" nested)
        (insert "Not directly in diario"))
      (my-dct-test--due later "2026-06-20 Sat")
      (should (equal (my-dc--day-files "20260603") (list target)))
      (should (equal (my-diario-agenda-files "20260603") (list target later)))
      (should (equal (my-diario-agenda-files "20260602") (list source later)))
      (should (equal (my-diario-refresh-agenda) (list target later)))
      (should (equal (caar (my-diario-refile-targets)) target))
      (should (string-match-p my-dc--refile-regexp "* SHALLOW"))
      (should (string-match-p my-dc--refile-regexp "** Empresa"))
      (should-not (string-match-p my-dc--refile-regexp "* TASKS"))
      (should-not (string-match-p my-dc--refile-regexp "* OPORTUNIDADES Y AMENAZAS")))))

(ert-deftest my-diario-commands-refile-only-managed-destinations ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--refile-layout))
    (with-current-buffer (find-file-noselect target)
      (should (equal denote-journal-directory dir))
      (my-diario-refile-targets)
      (should (eq org-refile-target-verify-function #'my-dc--refile-verify))
      (let ((names (mapcar (lambda (item)
                             (save-excursion
                               (goto-char (nth 3 item))
                               (org-get-heading t t t t)))
                           (org-refile-get-targets))))
        (should (equal (sort names #'string<)
                       '("Contratista" "DEEP" "Empresa" "SHALLOW"))))
      (goto-char (point-min))
      (search-forward "* OPORTUNIDADES Y AMENAZAS")
      (beginning-of-line)
      (should-not (string-match-p my-dc--refile-regexp
                                  (buffer-substring-no-properties
                                   (line-beginning-position) (line-end-position))))
      (should-not (funcall org-refile-target-verify-function))
      (goto-char (point-min))
      (search-forward "** Empresa :impostor:")
      (beginning-of-line)
      (should (string-match-p my-dc--refile-regexp
                              (buffer-substring-no-properties
                               (line-beginning-position) (line-end-position))))
      (should-not (funcall org-refile-target-verify-function))
      (goto-char (point-min))
      (search-forward "** Empresa :empleo:")
      (beginning-of-line)
      (should (funcall org-refile-target-verify-function))
      (let ((org-refile-target-verify-function
             (lambda () (not (equal (org-get-heading t t t t) "SHALLOW")))))
        (my-diario-refile-targets)
        (should (= 3 (length (org-refile-get-targets))))))))

(ert-deftest my-diario-commands-first-day-retrieves-due ()
  (my-dct-test--with-files
    (delete-file source)
    (my-dct-test--due later)
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args)
                   (cl-incf created)
                   (with-temp-file target (insert my-dct-test--fresh))
                   target)))
        (let ((result (my-diario-today)))
          (should (= 1 created))
          (should (equal (plist-get result :target) target))
          (should (= 1 (plist-get result :returned)))
          (should (string-match-p "\\*\\* NEXT Esperando" (my-dct-test--text target)))
          (should (string-match-p "\\*\\* Empresa" (my-dct-test--text target)))
          (should (string-match-p "Nota anidada" (my-dct-test--text target)))
          (should-not (string-match-p "Esperando" (my-dct-test--text later))))))))

(ert-deftest my-diario-commands-new-day-rolls-once ()
  (my-dct-test--with-files
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args)
                   (cl-incf created)
                   (with-temp-file target (insert my-dct-test--fresh))
                   target)))
        (let ((result (my-diario-today)))
          (should (= 1 created))
          (should (eq (plist-get result :mode) 'new))
          (should (= 1 (plist-get result :moved)))
          (should (= 1 (plist-get result :parked)))
          (should (string-match-p "\\*\\*\\* TODO Encargo" (my-dct-test--text target)))
          (should (string-match-p "\\*\\* TODO Trabajo" (my-dct-test--text target)))
          (should-not (string-match-p "\\*\\* TODO Trabajo" (my-dct-test--text source)))
          (should (string-match-p "Texto fuera de listas" (my-dct-test--text target)))
          (should (string-match-p "\\*\\* COLD Más tarde" (my-dct-test--text later)))
          (should (= 0 (plist-get (my-diario-today) :returned)))
          (should (= 1 created)))))))

(ert-deftest my-diario-commands-existing-today-no-old-copy ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--ready))
    (my-dct-test--due later)
    (let ((old (my-dct-test--text source)))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args) (error "Existing day called Denote"))))
        (should (= 1 (plist-get (my-diario-today) :returned)))
        (should (= 0 (plist-get (my-diario-today) :returned))))
      (should (equal old (my-dct-test--text source)))
      (should (string-match-p "Decisión de hoy" (my-dct-test--text target)))
      (should (string-match-p "NEXT Esperando" (my-dct-test--text target)))
      (should-not (string-match-p "TODO Trabajo" (my-dct-test--text target))))))

(ert-deftest my-diario-commands-existing-fresh-rolls-source ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--fresh))
    (my-dct-test--due later)
    (let ((result (my-diario-today)))
      (should (= 1 (plist-get result :moved)))
      (should (= 1 (plist-get result :returned))))
    (should (string-match-p "NEXT Esperando" (my-dct-test--text target)))
    (should (string-match-p "TODO Trabajo" (my-dct-test--text target)))
    (should-not (string-match-p "TODO Trabajo" (my-dct-test--text source)))))

(ert-deftest my-diario-commands-retry-with-task-receipts ()
  (my-dct-test--with-files
    (let ((real-save (symbol-function 'my-diario--save))
          (failed nil))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args)
                   (with-temp-file target (insert my-dct-test--fresh)) target))
                ((symbol-function 'my-diario--save)
                 (lambda (path before text)
                   (when (and (equal path target) (not failed))
                     (setq failed t)
                     (error "Injected target save failure"))
                   (funcall real-save path before text))))
        (should-error (my-diario-today)))
      (should (string-match-p "DIARIO_ROLL_TO" (my-dct-test--text source)))
      (should-not (string-match-p "TODO Trabajo" (my-dct-test--text target)))
      (should (= 1 (plist-get (my-diario-today) :moved)))
      (should (string-match-p "TODO Trabajo" (my-dct-test--text target)))
      (should-not (string-match-p "TODO Trabajo" (my-dct-test--text source))))))

(ert-deftest my-diario-commands-recover-ot-notes-without-task-receipt ()
  (my-dct-test--with-files
    (with-temp-file source
      (insert "#+title: Ayer\n#+identifier: 20260601T1100\n\n* OPORTUNIDADES Y AMENAZAS\n** Empresa\n*** TODO OT sin tarea :cliente_003:\n** Contratista\n* DEEP\n* SHALLOW\n* Notas\nContexto que viaja.\n"))
    (let ((save (symbol-function 'my-diario--save))
          (failed nil)
          (created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args)
                   (cl-incf created)
                   (with-temp-file target (insert my-dct-test--fresh)) target))
                ((symbol-function 'my-diario--save)
                 (lambda (file before content)
                   (when (and (equal file target) (not failed))
                     (setq failed t)
                     (error "Injected first target write failure"))
                   (funcall save file before content))))
        (should-error (my-diario-today)))
      (should (= 1 created))
      (should-not (string-match-p "DIARIO_ROLL_TO" (my-dct-test--text source)))
      (should (equal my-dct-test--fresh (my-dct-test--text target)))
      (let ((result (my-diario-today)))
        (should (= 1 (plist-get result :copied-ot)))
        (should (eq (plist-get result :mode) 'new)))
      (let ((new (my-dct-test--text target)))
        (should (= 1 (my-dct-test--count new "*** TODO OT sin tarea")))
        (should (= 1 (my-dct-test--count new "Contexto que viaja.")))
        (should (string-search "*** TODO OT sin tarea" (my-dct-test--text source)))
        (should (equal new (progn (my-diario-today) (my-dct-test--text target))))))))

(ert-deftest my-diario-commands-existing-fresh-refuses-legacy-source ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--fresh))
    (with-temp-file source
      (insert "#+title: Ayer\n#+identifier: 20260601T1100\n* TASKS\n** TODO Sin clasificar\n"))
    (let ((reason (should-error (my-diario-today) :type 'user-error)))
      (should (string-match-p "my-diario-classify" (error-message-string reason))))
    (should (equal my-dct-test--fresh (my-dct-test--text target)))))

(ert-deftest my-diario-commands-existing-fresh-refuses-unsaved-source ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--fresh))
    (with-current-buffer (find-file-noselect source)
      (goto-char (point-max)) (insert "Cambio sin guardar"))
    (should-error (my-diario-today) :type 'user-error)
    (should (equal my-dct-test--fresh (my-dct-test--text target)))))

(ert-deftest my-diario-commands-existing-fresh-rejects-bad-metadata ()
  (my-dct-test--with-files
    (with-temp-file target
      (insert (replace-regexp-in-string
               "20260603T0900" "otro-id" my-dct-test--fresh t t)))
    (let ((before (my-dct-test--text source)))
      (should-error (my-diario-today) :type 'user-error)
      (should (equal before (my-dct-test--text source))))))

(ert-deftest my-diario-commands-unsaved-source-and-target ()
  (my-dct-test--with-files
    (with-current-buffer (find-file-noselect source)
      (goto-char (point-max)) (insert "Unsaved source"))
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args) (cl-incf created))))
        (should-error (my-diario-today) :type 'user-error))
      (should (= 0 created))
      (should-not (file-exists-p target)))
    (with-current-buffer (find-buffer-visiting source)
      (set-buffer-modified-p nil) (revert-buffer t t))
    (with-temp-file target (insert my-dct-test--ready))
    (with-current-buffer (find-file-noselect target)
      (goto-char (point-max)) (insert "Unsaved target"))
    (should-error (my-diario-today) :type 'user-error)
    (should (equal my-dct-test--ready (my-dct-test--text target)))))

(ert-deftest my-diario-commands-live-legacy-refuses-before-denote ()
  (my-dct-test--with-files
    (with-current-buffer (find-file-noselect source)
      (goto-char (point-max))
      (insert "* TASKS\n** TODO En vivo\n"))
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args) (cl-incf created))))
        (let ((reason (should-error (my-diario-today) :type 'user-error)))
          (should (string-match-p "my-diario-classify" (error-message-string reason)))))
      (should (= 0 created)))))

(ert-deftest my-diario-commands-later-conflict-before-creation ()
  (my-dct-test--with-files
    (my-dct-test--due later)
    (with-current-buffer (find-file-noselect later)
      (goto-char (point-max)) (insert "Unsaved LUEGO"))
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args) (cl-incf created))))
        (should-error (my-diario-today) :type 'user-error))
      (should (= 0 created)))))

(ert-deftest my-diario-commands-legacy-luego-refuses-before-denote ()
  (my-dct-test--with-files
    (with-temp-file later
      (insert "* TASKS\n** COLD Sin origen\nSCHEDULED: <2026-06-03 Wed>\n"))
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args) (cl-incf created))))
        (let ((reason (should-error (my-diario-today) :type 'user-error)))
          (should (string-match-p "my-diario-reconcile-luego"
                                  (error-message-string reason)))))
      (should (= 0 created)))))

(ert-deftest my-diario-commands-source-legacy-and-finish ()
  (my-dct-test--with-files
    (with-temp-file source
      (insert "#+title: Ayer\n#+identifier: 20260601T1100\n* TASKS\n** TODO Pendiente\n* Notas\nContexto.\n"))
    (let ((created 0))
      (cl-letf (((symbol-function 'denote)
                 (lambda (&rest _args) (cl-incf created))))
        (let ((reason (should-error (my-diario-today) :type 'user-error)))
          (should (string-match-p "my-diario-classify" (error-message-string reason)))))
      (should (= 0 created)))
    (with-current-buffer (find-file-noselect source)
      (should-error (my-diario-finish) :type 'user-error)
      (my-diario-prepare)
      (goto-char (point-min))
      (search-forward "** TODO Pendiente")
      (my-diario-classify "SHALLOW")
      (my-diario-finish)
      (should-not (string-match-p "\\* TASKS" (buffer-string)))
      (should (buffer-modified-p))
      (should (string-match-p "\\* TASKS" (my-dct-test--text source)))
      (should-error (my-diario-today) :type 'user-error)
      (save-buffer))
    (cl-letf (((symbol-function 'denote)
               (lambda (&rest _args)
                 (with-temp-file target (insert my-dct-test--fresh)) target)))
      (my-diario-today))
    (should (string-match-p "\\*\\* TODO Pendiente" (my-dct-test--text target)))
    (should-not (string-match-p "\\* TASKS" (my-dct-test--text target)))))

(ert-deftest my-diario-commands-finish-preserves-prose-and-undo ()
  (with-temp-buffer
    (let ((org-mode-hook nil)) (org-mode))
    (insert "* TASKS\nIdeas sin clasificar como entradas.\n* Notas\nOtro texto.\n")
    (setq buffer-undo-list nil)
    (let ((old (buffer-string)))
      (my-diario-finish)
      (should (string-match-p "Notas (antes TASKS)\nIdeas sin clasificar" (buffer-string)))
      (should (string-match-p "\\* Notas\nOtro texto" (buffer-string)))
      (undo 1)
      (should (equal old (buffer-string))))))

(ert-deftest my-diario-commands-legacy-luego-explicit-origins ()
  (my-dct-test--with-files
    (with-temp-file later
      (insert "* TASKS\n** COLD OT :cliente_003:\nSCHEDULED: <2026-06-20 Sat>\n:PROPERTIES:\n:ID: unique-legacy-id\n:END:\nEnlace [[denote:20260511T1358]].\n*** Nota de OT\nTexto interior.\n** COLD Profundo\n** COLD Ligero\nSCHEDULED: <2026-06-02 Tue>\n"))
    (let ((answers '("OT Empresa" "DEEP" "SHALLOW"))
          (ids 0)
          (org-id-method 'ts)
          (original (my-dct-test--text later)))
      (with-current-buffer (find-file-noselect later)
        (setq buffer-undo-list nil)
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_prompt choices &rest _args)
                     (should (equal choices my-dmig--choices))
                     (pop answers)))
                  ((symbol-function 'org-id-new)
                   (lambda (&rest _args)
                     (should (eq org-id-method 'uuid))
                     (format "fixture-uuid-%s" (cl-incf ids))))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (&rest _args)
                     (error "Noninteractive reconciliation changed windows"))))
          (should (eq (my-diario-reconcile-luego later "20260603") (current-buffer))))
        (should (null answers))
        (should (= ids 3))
        (should (eq org-id-method 'ts))
        (should (buffer-modified-p))
        (should (equal original (my-dct-test--text later)))
        (should (string-match-p "\\* LUEGO" (buffer-string)))
        (should (string-match-p "SCHEDULED: <2026-06-17" (buffer-string)))
        (should (string-match-p "SCHEDULED: <2026-06-20" (buffer-string)))
        (should (string-match-p "SCHEDULED: <2026-06-02" (buffer-string)))
        (should (string-match-p "unique-legacy-id" (buffer-string)))
        (should (string-match-p "Enlace \\[\\[denote:" (buffer-string)))
        (should (string-match-p "\\*\\*\\* Nota de OT" (buffer-string)))
        (my-diario--later-scan)
        (goto-char (point-min))
        (search-forward "** COLD OT")
        (should (equal (org-entry-get nil "DIARIO_ORIGIN_HASH")
                       (my-diario--origin-hash "fixture-uuid-1"
                                               "OPORTUNIDADES Y AMENAZAS" "Empresa")))
        (undo 1)
        (should (equal original (buffer-string)))))))

(ert-deftest my-diario-commands-interactive-luego-opens-edited-buffer ()
  (my-dct-test--with-files
    (with-temp-file later
      (insert "* TASKS\n** COLD Revisión\nSCHEDULED: <2026-06-20 Sat>\n"))
    (let (shown (displays 0))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "SHALLOW"))
                ((symbol-function 'org-id-new)
                 (lambda (&rest _args) "fixture-uuid"))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buffer &rest _args)
                   (setq shown buffer)
                   (cl-incf displays))))
        (let ((returned (call-interactively #'my-diario-reconcile-luego)))
          (should (eq shown returned))))
      (should (= displays 1))
      (with-current-buffer shown
        (should (buffer-modified-p))
        (should (string-match-p "^\\* LUEGO" (buffer-string))))
      (should (string-match-p "^\\* TASKS" (my-dct-test--text later))))))

(ert-deftest my-diario-commands-legacy-luego-rejects-partial-metadata ()
  (my-dct-test--with-files
    (with-temp-file later (insert "* TASKS\n** COLD Incompleto\n:PROPERTIES:\n:DIARIO_LIST: SHALLOW\n:END:\n"))
    (with-current-buffer (find-file-noselect later)
      (let ((before (buffer-string)))
        (should-error (my-diario-reconcile-luego later "20260603") :type 'user-error)
        (should (equal before (buffer-string)))
        (should-not (buffer-modified-p))))))

(ert-deftest my-diario-commands-future-luego-not-returned ()
  (my-dct-test--with-files
    (with-temp-file target (insert my-dct-test--ready))
    (my-dct-test--due later "2026-06-20 Sat")
    (should (= 0 (plist-get (my-diario-today) :returned)))
    (should-not (string-match-p "Esperando" (my-dct-test--text target)))
    (should (string-match-p "Esperando" (my-dct-test--text later)))))

(ert-deftest my-diario-commands-focus-scope-and-manual-activation ()
  (my-dct-test--with-files
    (let ((global-before (lookup-key (current-global-map) (kbd "C-c n f"))))
      (with-current-buffer (find-file-noselect source)
        (should-not my-diario-focus-mode)
        (my-diario-activate-focus)
        (should my-diario-focus-mode)
        (should (eq (key-binding (kbd "C-c n f")) #'my-diario-focus)))
      (with-temp-file target (insert my-dct-test--ready))
      (let ((org-mode-hook '(my-diario-activate-focus)))
        (with-current-buffer (find-file-noselect target)
          (should my-diario-focus-mode)
          (should (eq (key-binding (kbd "C-c n f")) #'my-diario-focus))))
      (let ((other (expand-file-name "other.org" dir)))
        (with-temp-file other (insert "* Otra nota\n"))
        (with-current-buffer (find-file-noselect other)
          (my-diario-activate-focus)
          (should-not my-diario-focus-mode)
          (should-not (eq (key-binding (kbd "C-c n f")) #'my-diario-focus))))
      (should (equal global-before (lookup-key (current-global-map)
                                               (kbd "C-c n f")))))))

(provide 'test-diario-commands)
;;; test-diario-commands.el ends here
