;;; test-diario-priad-commands.el --- Isolated PRIAD command fixtures -*- lexical-binding: t; -*-

;;; Commentary:
;; Never load setup-journaling or visit a live KB file.  Inspect its thin
;; wrappers as data; exercise the bridge against temporary Org visitors.

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'org)
(require 'diario-priad-commands)

(defvar denote-directory)
(defvar denote-journal-directory)
(defvar my-diario-customer-tags)
(defvar my-diario-ignored-tags)
(defvar my-dpc--inhibit-import)

(defconst my-dpc-test--setup
  (expand-file-name "setup-journaling.el"
                    (expand-file-name ".." (file-name-directory
                                           (or load-file-name buffer-file-name)))))
(defconst my-dpc-test--source
  "#+title: Cliente\n\n* Ideas :plan:\n** TODO Cotización :cliente_techo:\nContexto [[denote:20260511T1358]].\n*** TODO Paso interno\n")
(defconst my-dpc-test--diario
  "#+title: Hoy\n#+identifier: 20260603T0900\n\n* OPORTUNIDADES Y AMENAZAS\n** Empresa\n** Contratista\n* DEEP\n* SHALLOW\n* Notas\n")
(defconst my-dpc-test--closed
  "#+title: Hoy\n#+identifier: 20260603T0900\n\n* OPORTUNIDADES Y AMENAZAS\n** Empresa\n*** DONE Cierre :cliente_techo:\n*** COLD Aparcado :cliente_techo:\n** Contratista\n* DEEP\n** DONE Medir :cliente_techo:\n* SHALLOW\n** DONE Llamar :cliente_techo:\n* Notas\n** DONE Fuera :cliente_techo:\n")

(defmacro my-dpc-test--files (&rest body)
  "Run BODY in a saved PRIAD source with bounded disposable visitors."
  (declare (indent 0) (debug t))
  `(with-temp-buffer
     (let* ((sandbox (make-temp-file "diario-priad-commands-test-" t))
            (denote-directory (expand-file-name "priads" sandbox))
            (denote-journal-directory (expand-file-name "diario" denote-directory))
            (source (expand-file-name
                     "20260601T1200==p--cliente__cliente.org" denote-directory))
            (target (expand-file-name
                     "20260603T0900--hoy__journal.org" denote-journal-directory))
            (next (expand-file-name
                   "20260604T0900--manana__journal.org" denote-journal-directory))
            (priad (expand-file-name
                    "20260601T1201==r--cliente__cliente.org" denote-directory))
            (real-find (symbol-function 'find-file-noselect))
            (fixture-root denote-directory)
            (fixture-journal denote-journal-directory)
            (org-mode-hook nil)
            (find-file-hook nil)
            (kill-buffer-query-functions nil)
            (kill-buffer-hook nil)
            (org-todo-keywords '((sequence "TODO" "NEXT" "WAIT" "SDM"
                                          "COLD" "|" "DONE" "KILL")))
            (my-diario-customer-tags nil)
            (my-diario-ignored-tags
             (append my-diario-ignored-tags '("chulet" "adm" "alf" "techo")))
            (org-log-done nil)
            (org-log-into-drawer nil)
            (org-inhibit-startup t))
       (make-directory denote-journal-directory t)
       (unwind-protect
           (progn
             (with-temp-file source (insert my-dpc-test--source))
             (with-temp-file target (insert my-dpc-test--diario))
             (with-temp-file next (insert my-dpc-test--diario))
             (with-temp-file priad (insert "#+title: Cliente\n* Bitácora\nNotas.\n"))
             (cl-letf (((symbol-function 'find-file-noselect)
                        (lambda (file &rest args)
                          (unless (and (stringp file)
                                       (file-in-directory-p (expand-file-name file)
                                                            fixture-root))
                            (error "Fixture cannot visit %S" file))
                          (let ((visitor (apply real-find file args)))
                            (with-current-buffer visitor
                              (setq-local denote-directory fixture-root)
                              (setq-local denote-journal-directory
                                          fixture-journal))
                            visitor))))
               (with-current-buffer (find-file-noselect source)
                 (org-mode)
                 ,@body)))
         (dolist (file (directory-files denote-directory t "\\.org\\'"))
           (when-let* ((visitor (find-buffer-visiting file)))
             (with-current-buffer visitor
               (let ((my-dpc--inhibit-import t)
                     (kill-buffer-query-functions nil)
                     (kill-buffer-hook nil))
                 (set-buffer-modified-p nil)
                 (kill-buffer visitor)))))
         (dolist (file (directory-files denote-journal-directory t "\\.org\\'"))
           (when-let* ((visitor (find-buffer-visiting file)))
             (with-current-buffer visitor
               (let ((my-dpc--inhibit-import t)
                     (kill-buffer-query-functions nil)
                     (kill-buffer-hook nil))
                 (set-buffer-modified-p nil)
                 (kill-buffer visitor)))))
         (delete-directory sandbox t)))))

(defun my-dpc-test--disk (file)
  "Read fixture FILE without a visiting buffer."
  (with-temp-buffer (insert-file-contents file) (buffer-string)))

(defun my-dpc-test--at (heading)
  "Move to fixture HEADING."
  (goto-char (point-min))
  (re-search-forward (concat "^\\*+ .*" (regexp-quote heading)))
  (beginning-of-line))

(defun my-dpc-test--count (fragment text)
  "Count literal FRAGMENT in TEXT."
  (let ((start 0) (count 0))
    (while (string-match (regexp-quote fragment) text start)
      (cl-incf count)
      (setq start (match-end 0)))
    count))

(defun my-dpc-test--form (name)
  "Read a setup-journaling defun with NAME without loading its side effects."
  (with-temp-buffer
    (insert-file-contents my-dpc-test--setup)
    (goto-char (point-min))
    (re-search-forward (concat "^(defun " (regexp-quote (symbol-name name)) " "))
    (beginning-of-line)
    (read (current-buffer))))

(ert-deftest my-diario-priad-commands-public-wiring ()
  (dolist (pair '((my-copiar-a-tareas-diarias . my-dpc-copy)
                  (my-copiar-a-tareas-diarias--maybe-on-kill . my-dpc-maybe-on-kill)
                  (my-referir-pendientes . my-dpc-refer)
                  (my-denote-journal-today . my-diario-today)))
    (let ((form (my-dpc-test--form (car pair))))
      (should (memq (car pair) form))
      (should (memq (cdr pair) (flatten-tree form)))))
  (with-temp-buffer
    (insert-file-contents my-dpc-test--setup)
    (dolist (binding '(("C-c n c" . "my-copiar-a-tareas-diarias")
                       ("C-c n e" . "my-referir-pendientes")
                       ("C-c n j" . "my-denote-journal-today")
                       ("C-c n a" . "my-org-agenda-current-file")))
      (goto-char (point-min))
      (should (search-forward (concat "(kbd \"" (car binding) "\") #'"
                                      (cdr binding)) nil t)))
    (goto-char (point-min))
    (should (search-forward "(add-hook 'org-mode-hook #'my-diario-activate-focus)" nil t))
    (goto-char (point-min))
    (should (search-forward "(setq my-diario-ignored-tags" nil t)))
  (let* ((copy (my-dpc-test--form 'my-copiar-a-tareas-diarias))
         (wrapper (eval `(lambda ,(nth 2 copy) ,@(cdddr copy)) t))
         (policy nil))
    (should (equal (nth 4 copy)
                   '(interactive (list (if current-prefix-arg
                                           'repeat 'new-only)))))
    (cl-letf (((symbol-function 'my-dpc-copy)
               (lambda (argument) (setq policy argument) :delegated)))
      (should (eq (funcall wrapper 'repeat) :delegated))
      (should (eq policy 'repeat))
      (should (eq (funcall wrapper) :delegated))
      (should-not policy)))
  (let ((refer (my-dpc-test--form 'my-referir-pendientes)))
    (cl-letf (((symbol-function 'my-dpc-refer) (lambda () :delegated)))
      (should (eq (funcall (eval `(lambda ,(nth 2 refer) ,@(cdddr refer)) t))
                  :delegated)))))

(ert-deftest my-diario-priad-commands-manual-import-close-once ()
  (my-dpc-test--files
    (let ((visitor (current-buffer)) (calls 0))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
                ((symbol-function 'completing-read)
                 (lambda (prompt &rest _)
                   (should (string-prefix-p "Importar a:" prompt))
                   "DEEP")))
        (let ((original (symbol-function 'my-diario-import))
              (kill-buffer-query-functions
               (list #'my-dpc-maybe-on-kill)))
          (cl-letf (((symbol-function 'my-diario-import)
                     (lambda (&rest args)
                       (cl-incf calls)
                       (apply original args))))
            (let ((this-command 'kill-buffer))
              (should (my-dpc-copy 'new-only))))))
      (should (= calls 1))
      (should-not (buffer-live-p visitor))
      (should (string-match-p "\\*\\* TODO Cotización" (my-dpc-test--disk target)))
      (should-not (string-search "* TASKS" (my-dpc-test--disk target)))
      (should (string-search ":DIARIO_EXPORTS:" (my-dpc-test--disk source))))))

(ert-deftest my-diario-priad-commands-failure-and-cancel-leave-source-open ()
  (my-dpc-test--files
    (let ((visitor (current-buffer))
          (before (my-dpc-test--disk source)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () nil)))
        (should-error (my-dpc-copy) :type 'user-error))
      (should (buffer-live-p visitor))
      (should (equal before (my-dpc-test--disk source)))
      (goto-char (point-max))
      (insert "Cambio sin guardar.\n")
      (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
                ((symbol-function 'y-or-n-p) (lambda (&rest _) nil)))
        (should-error (my-dpc-copy) :type 'user-error))
      (should (buffer-live-p visitor))
      (should (buffer-modified-p))
      (should (equal before (my-dpc-test--disk source))))))

(ert-deftest my-diario-priad-commands-close-no-new-work-no-diary ()
  (my-dpc-test--files
    (erase-buffer)
    (insert "* DONE Terminado\n:PROPERTIES:\n:DIARIO_REF_KEY: histórico\n:END:\n** TODO Histórico\n")
    (save-buffer)
    (let ((visitor (current-buffer))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current)
                 (lambda () (error "No diario should be needed")))
                ((symbol-function 'completing-read)
                 (lambda (&rest _) (error "No classification should be needed"))))
        (let ((this-command 'kill-buffer))
          (should (kill-buffer visitor))))
      (should-not (buffer-live-p visitor)))))

(ert-deftest my-diario-priad-commands-receipted-close-without-diary ()
  (my-dpc-test--files
    (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
              ((symbol-function 'completing-read) (lambda (&rest _) "SHALLOW")))
      (should (= 1 (plist-get (my-dpc--import) :copied))))
    (let ((visitor (current-buffer))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current)
                 (lambda () (error "An exported PRIAD should not need a diary")))
                ((symbol-function 'completing-read)
                 (lambda (&rest _) (error "Exported root asked for a list"))))
        (let ((this-command 'kill-buffer))
          (should (kill-buffer visitor))))
      (should-not (buffer-live-p visitor))
      (should (= 1 (my-dpc-test--count "** TODO Cotización"
                                      (my-dpc-test--disk target)))))))

(ert-deftest my-diario-priad-commands-user-close-and-background-close ()
  (my-dpc-test--files
    (let ((visitor (current-buffer))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      ;; Background closing must not even attempt a diario lookup.
      (cl-letf (((symbol-function 'my-diario-current)
                 (lambda () (error "Background hook attempted import"))))
        (let ((this-command nil))
          (should (kill-buffer visitor))))
      (should (equal (my-dpc-test--disk source) my-dpc-test--source)))
    (with-current-buffer (find-file-noselect source)
      (let ((visitor (current-buffer))
            (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
        (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
                  ((symbol-function 'completing-read) (lambda (&rest _) "SHALLOW")))
          (let ((this-command 'kill-this-buffer))
            (should (kill-buffer visitor))))
        (should-not (buffer-live-p visitor))
        (should (string-search "** TODO Cotización" (my-dpc-test--disk target)))))))

(ert-deftest my-diario-priad-commands-user-close-failure-keeps-priad ()
  (my-dpc-test--files
    (let ((visitor (current-buffer))
          (before (my-dpc-test--disk source))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () nil)))
        (let ((this-command 'kill-buffer))
          (should-error (kill-buffer visitor) :type 'user-error)))
      (should (buffer-live-p visitor))
      (should (equal before (my-dpc-test--disk source))))))

(ert-deftest my-diario-priad-commands-internal-close-inhibited ()
  (my-dpc-test--files
    (let ((kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current)
                 (lambda () (error "Internal close attempted import"))))
        (let ((my-dpc--inhibit-import t)
              (this-command 'kill-buffer))
          (should (kill-buffer (current-buffer))))))
    (should (equal my-dpc-test--source (my-dpc-test--disk source)))))

(ert-deftest my-diario-priad-commands-repeat-before-write-command-retry ()
  (my-dpc-test--files
    (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
              ((symbol-function 'completing-read) (lambda (&rest _) "DEEP")))
      (should (= 1 (plist-get (my-dpc--import) :copied))))
    (let ((visitor (current-buffer))
          (before (my-dpc-test--disk next))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () next))
                ((symbol-function 'my-di--save-target)
                 (lambda (&rest _) (user-error "Injected repeat target failure")))
                ((symbol-function 'completing-read)
                 (lambda (&rest _) (error "Repeat asked for classification"))))
        (should-error (my-dpc-copy 'repeat) :type 'user-error))
      (should (buffer-live-p visitor))
      (should (string-search ":DIARIO_EXPORT_PENDING:"
                             (my-dpc-test--disk source)))
      (should (equal before (my-dpc-test--disk next)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () target)))
        (should-error (my-dpc-copy 'new-only) :type 'user-error))
      (should (buffer-live-p visitor))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () next))
                ((symbol-function 'completing-read)
                 (lambda (&rest _) (error "Retry asked for classification"))))
        (let ((this-command 'kill-buffer))
          (should (my-dpc-copy 'new-only))))
      (should-not (buffer-live-p visitor))
      (should (= 1 (my-dpc-test--count "** TODO Cotización"
                                      (my-dpc-test--disk next))))
      (should-not (string-search ":DIARIO_EXPORT_PENDING:"
                                 (my-dpc-test--disk source))))))

(ert-deftest my-diario-priad-commands-repeat-before-write-kill-hook-retry ()
  (my-dpc-test--files
    (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
              ((symbol-function 'completing-read) (lambda (&rest _) "SHALLOW")))
      (should (= 1 (plist-get (my-dpc--import) :copied))))
    (let ((visitor (current-buffer))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () next))
                ((symbol-function 'my-di--save-target)
                 (lambda (&rest _) (user-error "Injected repeat target failure"))))
        (should-error (my-dpc--import 'repeat) :type 'user-error))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () target)))
        (let ((this-command 'kill-buffer))
          (should-error (kill-buffer visitor) :type 'user-error)))
      (should (buffer-live-p visitor))
      (should-not (string-search "** TODO Cotización" (my-dpc-test--disk next)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () next))
                ((symbol-function 'completing-read)
                 (lambda (&rest _) (error "Close retry asked for classification"))))
        (let ((this-command 'kill-buffer))
          (should (kill-buffer visitor))))
      (should-not (buffer-live-p visitor))
      (should (= 1 (my-dpc-test--count "** TODO Cotización"
                                      (my-dpc-test--disk next))))
      (should-not (string-search ":DIARIO_EXPORT_PENDING:"
                                 (my-dpc-test--disk source))))))

(ert-deftest my-diario-priad-commands-explicit-repeat ()
  (my-dpc-test--files
    (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
              ((symbol-function 'completing-read) (lambda (&rest _) "SHALLOW")))
      (should (= 1 (plist-get (my-dpc--import 'new-only) :copied))))
    (let ((before (my-dpc-test--disk next)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () next))
                ((symbol-function 'completing-read)
                 (lambda (&rest _) (error "Cached destination was not used"))))
        (should-not (my-dpc--import 'new-only))
        (should (equal before (my-dpc-test--disk next)))
        (should (= 1 (plist-get (my-dpc--import 'repeat) :copied)))
        (should (= 1 (plist-get (my-dpc--import 'repeat) :already))))
      (should (= 1 (my-dpc-test--count "** TODO Cotización"
                                      (my-dpc-test--disk next)))))))

(ert-deftest my-diario-priad-commands-import-destination-conflict ()
  (my-dpc-test--files
    (with-current-buffer (find-file-noselect target)
      (goto-char (point-max))
      (insert "Sin guardar.\n"))
    (let ((visitor (current-buffer))
          (before (my-dpc-test--disk source)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
                ((symbol-function 'completing-read) (lambda (&rest _) "DEEP")))
        (should-error (my-dpc-copy) :type 'user-error))
      (should (buffer-live-p visitor))
      (should (equal before (my-dpc-test--disk source)))
      (should-not (string-search "Sin guardar" (my-dpc-test--disk target))))))

(ert-deftest my-diario-priad-commands-referring-before-first-heading ()
  (my-dpc-test--files
    (with-temp-file target (insert my-dpc-test--closed))
    (with-current-buffer (find-file-noselect target)
      (goto-char (point-min))
      (insert "Nota sin guardar.\n")
      (cl-letf (((symbol-function 'y-or-n-p)
                 (lambda (&rest _) (error "No heading must not ask to save"))))
        (should-error (my-dpc-refer) :type 'user-error))
      (should (buffer-modified-p))
      (should-not (string-search "Nota sin guardar" (my-dpc-test--disk target))))))

(ert-deftest my-diario-priad-commands-referring-scope-and-cold ()
  (my-dpc-test--files
    (with-temp-file target (insert my-dpc-test--closed))
    (with-current-buffer (find-file-noselect target)
      (cl-letf (((symbol-function 'my-dpc--candidates) (lambda () (list priad))))
        (my-dpc-test--at "OPORTUNIDADES Y AMENAZAS")
        (should (= 1 (plist-get (my-dpc-refer) :copied)))
        (should-not (string-search "COLD Aparcado" (my-dpc-test--disk priad)))
        (should-not (string-search "Medir" (my-dpc-test--disk priad)))
        (my-dpc-test--at "DEEP")
        (should (= 1 (plist-get (my-dpc-refer) :copied)))
        (my-dpc-test--at "SHALLOW")
        (should (= 0 (plist-get (my-dpc-refer) :copied)))
        (my-dpc-test--at "Notas")
        (should (= 0 (plist-get (my-dpc-refer) :copied)))
        (should (string-search "DONE Cierre" (my-dpc-test--disk target)))
        (should (string-search "COLD Aparcado" (my-dpc-test--disk target)))
        (should (string-search "DONE Medir" (my-dpc-test--disk priad)))
        (should-not (string-search "* TASKS" (my-dpc-test--disk priad)))))))

(ert-deftest my-diario-priad-commands-referring-save-and-conflicts ()
  (my-dpc-test--files
    (with-temp-file target (insert my-dpc-test--closed))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (forward-line 1)
      (insert "Editado.\n")
      (forward-line -1)
      (cl-letf (((symbol-function 'my-dpc--candidates) (lambda () (list priad)))
                ((symbol-function 'y-or-n-p) (lambda (&rest _) nil)))
        (should-error (my-dpc-refer) :type 'user-error))
      (should-not (string-search "DIARIO_REF_KEY" (my-dpc-test--disk target)))
      (cl-letf (((symbol-function 'my-dpc--candidates) (lambda () (list priad)))
                ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
        (should (= 1 (plist-get (my-dpc-refer) :copied)))))
    (should (string-search "Editado" (my-dpc-test--disk target)))
    (should (string-search "Editado" (my-dpc-test--disk priad)))
    (with-current-buffer (find-file-noselect priad)
      (goto-char (point-max))
      (insert "Conflicto sin guardar.\n"))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Medir")
      (cl-letf (((symbol-function 'my-dpc--candidates) (lambda () (list priad))))
        (should-error (my-dpc-refer) :type 'user-error))
      (should-not (string-search "Medir" (my-dpc-test--disk priad)))
      (should (= 1 (my-dpc-test--count ":DIARIO_REF_KEY:"
                                      (my-dpc-test--disk target)))))))

(ert-deftest my-diario-priad-commands-stale-source-refused ()
  (my-dpc-test--files
    (with-temp-file target (insert my-dpc-test--closed))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (forward-line 1)
      (insert "Nota sin guardar.\n")
      (with-temp-file target (insert my-dpc-test--closed "Edición externa.\n"))
      (cl-letf (((symbol-function 'y-or-n-p)
                 (lambda (&rest _) (error "Stale source must not prompt to save"))))
        (should-error (my-dpc-refer) :type 'user-error))
      (should (buffer-modified-p))
      (should (string-search "Edición externa." (my-dpc-test--disk target)))
      (should-not (string-search "DIARIO_REF_KEY" (my-dpc-test--disk target)))
      (should-not (string-search "DONE Cierre" (my-dpc-test--disk priad))))))

(ert-deftest my-diario-priad-commands-active-root-discovery ()
  (my-dpc-test--files
    (let ((bad (expand-file-name "20260601T1300==p--sin-keywords.org" denote-directory))
          (archived (expand-file-name "20260601T1301==ap--viejo__cliente.org" denote-directory))
          (nested (expand-file-name "sub" denote-directory))
          (symlink (expand-file-name "20260601T1302==p--link__cliente.org" denote-directory)))
      (with-temp-file bad (insert "* Notas\n"))
      (with-temp-file archived (insert "* Notas\n"))
      (make-directory nested)
      (with-temp-file (expand-file-name "20260601T1303==r--nested__cliente.org" nested)
        (insert "* Notas\n"))
      (make-symbolic-link priad symlink)
      (should (equal (my-dpc--candidates) (list source priad)))
      (with-temp-file target (insert my-dpc-test--closed))
      (with-current-buffer (find-file-noselect target)
        (my-dpc-test--at "Cierre")
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (prompt choices &rest _)
                     (should (string-prefix-p "Elegir PRIAD:" prompt))
                     (should (equal choices (list source priad my-dp--omit)))
                     priad)))
          (should (= 1 (plist-get (my-dpc-refer) :copied)))))
      (should-not (string-search "DONE Cierre" (my-dpc-test--disk source)))
      (should (string-search "DONE Cierre" (my-dpc-test--disk priad))))))

(ert-deftest my-diario-priad-commands-denote-create-restores-point ()
  (my-dpc-test--files
    (with-temp-file target
      (insert (replace-regexp-in-string "cliente_techo" "nuevo_techo"
                                            my-dpc-test--closed t t)))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (let ((origin (current-buffer))
            (position (point))
            (new (expand-file-name "20260601T1400==p--nuevo__nuevo.org"
                                   denote-directory))
            (created 0))
        (cl-letf (((symbol-function 'denote) (lambda (&rest _) nil))
                  ((symbol-function 'completing-read)
                   (lambda (prompt _choices &rest _)
                     (should (string-prefix-p "Sin PRIAD:" prompt))
                     my-dp--create))
                  ((symbol-function 'call-interactively)
                   (lambda (command &rest _)
                     (should (eq command 'denote))
                     (cl-incf created)
                     (with-temp-file new (insert "#+title: Nuevo\n"))
                     (let ((buf (find-file-noselect new)))
                       (with-current-buffer buf
                         (goto-char (point-max))
                         (insert "Nota creada.\n"))
                       (set-buffer buf))
                     new)))
          (should (= 1 (plist-get (my-dpc-refer) :copied))))
        (should (= 1 created))
        (should (eq origin (current-buffer)))
        (should (= position (point)))
        (should (string-search "Nota creada." (my-dpc-test--disk new)))
        (should (string-search "DONE Cierre" (my-dpc-test--disk new)))))))

(ert-deftest my-diario-priad-commands-denote-unsaved-new-visitor ()
  (my-dpc-test--files
    (with-temp-file target
      (insert (replace-regexp-in-string "cliente_techo" "nuevo_techo"
                                            my-dpc-test--closed t t)))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (let ((origin (current-buffer))
            (position (point))
            (new (expand-file-name "20260601T1400==p--nuevo__nuevo.org"
                                   denote-directory)))
        (should-not (file-exists-p new))
        (cl-letf (((symbol-function 'denote) (lambda (&rest _) nil))
                  ((symbol-function 'completing-read)
                   (lambda (prompt _choices &rest _)
                     (should (string-prefix-p "Sin PRIAD:" prompt))
                     my-dp--create))
                  ((symbol-function 'call-interactively)
                   (lambda (command &rest _)
                     (should (eq command 'denote))
                     (let ((visitor (find-file-noselect new)))
                       (with-current-buffer visitor
                         (insert "#+title: Nuevo sin guardar\n"))
                       (should-not (file-exists-p new))
                       (set-buffer visitor))
                     new)))
          (should (= 1 (plist-get (my-dpc-refer) :copied))))
        (should (eq origin (current-buffer)))
        (should (= position (point)))
        (should (file-regular-p new))
        (should (string-search "Nuevo sin guardar" (my-dpc-test--disk new)))
        (should (string-search "DONE Cierre" (my-dpc-test--disk new)))))))

(ert-deftest my-diario-priad-commands-create-dirty-visitor-refused ()
  (my-dpc-test--files
    (let* ((existing (expand-file-name
                      "20260601T1400==p--otro__nuevo.org" denote-directory))
           (content "#+title: Otro archivo\n"))
      (with-temp-file existing (insert content))
      (let ((visitor (find-file-noselect existing))
            (origin (current-buffer))
            (position (point)))
        (with-current-buffer visitor
          (goto-char (point-max))
          (insert "Cambio ajeno sin guardar.\n"))
        (cl-letf (((symbol-function 'denote) (lambda (&rest _) nil))
                  ((symbol-function 'call-interactively)
                   (lambda (command &rest _)
                     (should (eq command 'denote))
                     (set-buffer visitor)
                     existing)))
          (should-error (my-dpc--create "nuevo" "nuevo_techo") :type 'user-error))
        (should (eq origin (current-buffer)))
        (should (= position (point)))
        (should (buffer-modified-p visitor))
        (should (equal content (my-dpc-test--disk existing)))))))

(ert-deftest my-diario-priad-commands-create-invalid-refused ()
  (my-dpc-test--files
    (with-temp-file target
      (insert (replace-regexp-in-string "cliente_techo" "nuevo_techo"
                                            my-dpc-test--closed t t)))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (let ((bad (expand-file-name "20260601T1400==p--mal__otro.org"
                                   denote-directory))
            (original (my-dpc-test--disk target)))
        (cl-letf (((symbol-function 'denote) (lambda (&rest _) nil))
                  ((symbol-function 'completing-read)
                   (lambda (&rest _) my-dp--create))
                  ((symbol-function 'call-interactively)
                   (lambda (_command &rest _)
                     (with-temp-file bad (insert "#+title: Mal\n"))
                     bad)))
          (should-error (my-dpc-refer) :type 'user-error))
        (should (equal original (my-dpc-test--disk target)))
        (should-not (string-search "DONE Cierre" (my-dpc-test--disk bad)))))))

(ert-deftest my-diario-priad-commands-create-cancel-and-invalid-paths ()
  (my-dpc-test--files
    (with-temp-file target
      (insert (replace-regexp-in-string "cliente_techo" "nuevo_techo"
                                            my-dpc-test--closed t t)))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (let ((original (my-dpc-test--disk target))
            (outside (expand-file-name "20260601T1400==p--new__nuevo.org" sandbox))
            (on-hold (expand-file-name "20260601T1401==sp--new__nuevo.org"
                                       denote-directory)))
        (cl-letf (((symbol-function 'denote) (lambda (&rest _) nil))
                  ((symbol-function 'completing-read)
                   (lambda (&rest _) my-dp--create)))
          (cl-letf (((symbol-function 'call-interactively)
                     (lambda (&rest _) (signal 'quit nil))))
            (should (= 1 (plist-get (my-dpc-refer) :unresolved))))
          (dolist (bad (list outside on-hold))
            (cl-letf (((symbol-function 'call-interactively)
                       (lambda (&rest _)
                         (with-temp-file bad (insert "#+title: No activo\n"))
                         bad)))
              (should-error (my-dpc-refer) :type 'user-error)))
          (should (equal original (my-dpc-test--disk target)))
          (should-not (string-search "DIARIO_REF_KEY" original)))))))

(ert-deftest my-diario-priad-commands-legacy-tags-shared-policy ()
  (my-dpc-test--files
    (with-temp-file target
      (insert (replace-regexp-in-string "cliente_techo" "cliente_techo:adm"
                                            my-dpc-test--closed t t)))
    (with-current-buffer (find-file-noselect target)
      (my-dpc-test--at "Cierre")
      (should (equal (my-diario-association-tags) '("cliente_techo")))
      (cl-letf (((symbol-function 'my-dpc--candidates) (lambda () (list priad))))
        (should (= 1 (plist-get (my-dpc-refer) :copied)))))
    (should (string-search "* OT cliente_techo" (my-dpc-test--disk priad)))))

(ert-deftest my-diario-priad-commands-keyless-receipt-close-after-new-day ()
  (my-dpc-test--files
    (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
              ((symbol-function 'completing-read) (lambda (&rest _) "DEEP")))
      (should (= 1 (plist-get (my-dpc--import) :copied))))
    (should-not (string-search "DIARIO_KEY" (my-dpc-test--disk target)))
    (let ((visitor (current-buffer))
          (next-before (my-dpc-test--disk next))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current)
                 (lambda () (error "A receipted close needs no new diary"))))
        (let ((this-command 'kill-buffer))
          (should (kill-buffer visitor))))
      (should-not (buffer-live-p visitor))
      (should (equal next-before (my-dpc-test--disk next)))
      (should (= 1 (my-dpc-test--count "** TODO Cotización"
                                      (my-dpc-test--disk target)))))))

(ert-deftest my-diario-priad-commands-pending-state-change-blocks-close ()
  (my-dpc-test--files
    (cl-letf (((symbol-function 'my-diario-current) (lambda () target))
              ((symbol-function 'completing-read) (lambda (&rest _) "SHALLOW"))
              ((symbol-function 'my-di--save-target)
               (lambda (&rest _) (user-error "Injected target failure"))))
      (should-error (my-dpc--import) :type 'user-error))
    (my-dpc-test--at "Cotización")
    (org-todo "DONE")
    (save-buffer)
    (let ((visitor (current-buffer))
          (kill-buffer-query-functions (list #'my-dpc-maybe-on-kill)))
      (cl-letf (((symbol-function 'my-diario-current) (lambda () target)))
        (let ((this-command 'kill-buffer))
          (should-error (kill-buffer visitor) :type 'user-error)))
      (should (buffer-live-p visitor))
      (should (string-search ":DIARIO_EXPORT_PENDING:"
                             (my-dpc-test--disk source)))
      (should-not (string-search "** TODO Cotización"
                                 (my-dpc-test--disk target))))))

(provide 'test-diario-priad-commands)
;;; test-diario-priad-commands.el ends here
